version: '3'
services:
  app:
    build:
      context: .
      args:
        - user=tewen
        - uid=501
    ports:
      - "80:8080"
      - "3030:3030"
    command: npm start
    restart: always

#  jobs:
#    build: ./jobs
#    command: npm run jobs
#    restart: always
